### ISSUE TITLE
download demo err

### ISSUE THREAD

**Issue by genffy** [fis-scaffold/laravel#1]
RT       ![qq 20150917160926](https://cloud.githubusercontent.com/assets/1506972/9928145/8b5f223a-5d56-11e5-83d1-30c76d289b77.png)

**Comment by 2betop** [comment]
你这是啥操作报的错误？

**Comment by 2betop** [comment]
多试几次吧，bos 镜像服务不稳定。

**Comment by genffy** [comment]
@2betop `fis3 init laravel` 这个操作。
多试几次，好吧。。。
