### ISSUE TITLE
unable to load plugin [fis3-hook-commonJs] or [fis-hook-commonJs]

### ISSUE THREAD

**Issue by kalsolio** [fis-scaffold/laravel#7]
npm install fis3-hook-commonjs
npm WARN package.json fisLaravelScaffold@1.0.0 No README data
npm WARN package.json fisLaravelScaffold@1.0.0 license should be a valid SPDX license expression
fis3-hook-commonjs@0.1.0 node_modules/fis3-hook-commonjs

fis3 release -d out

 [INFO] Currently running fis3 (/usr/lib/node_modules/fis3/)

 Ω
 [ERROR] unable to load plugin [fis3-hook-commonJs] or [fis-hook-commonJs]

**Comment by 2betop** [comment]
重试下

**Comment by kalsolio** [comment]
使用 fis3 init 的那个还没更新吧

**Comment by 2betop** [comment]
更新了：https://github.com/fis-scaffold/laravel/commit/4f9897f5703c9b83a32a76ccfa4ca6a2b1c353e5

主要问题是fis.hook 那个地方写错了，应该是 `commonjs` 而不是 `commonJs`
